Imports com.epson.bank.driver

Public Class Epson

    Public Shared Function GetErrorString(errResultCode As ErrorCode) As String
        Select Case errResultCode

            Case ErrorCode.SUCCESS
                Return ConstComStr.CAPTION_00_000
            Case ErrorCode.ERR_TYPE
                Return ConstComStr.CAPTION_03_000
            Case ErrorCode.ERR_OPENED
                Return ConstComStr.CAPTION_03_001
            Case ErrorCode.ERR_NO_PRINTER
                Return ConstComStr.CAPTION_03_002
            Case ErrorCode.ERR_NO_TARGET
                Return ConstComStr.CAPTION_03_003
            Case ErrorCode.ERR_NO_MEMORY
                Return ConstComStr.CAPTION_03_004
            Case ErrorCode.ERR_HANDLE
                Return ConstComStr.CAPTION_03_005
            Case ErrorCode.ERR_TIMEOUT
                Return ConstComStr.CAPTION_03_006
            Case ErrorCode.ERR_ACCESS
                Return ConstComStr.CAPTION_03_007
            Case ErrorCode.ERR_PARAM
                Return ConstComStr.CAPTION_03_008
            Case ErrorCode.ERR_NOT_SUPPORT
                Return ConstComStr.CAPTION_03_009
            Case ErrorCode.ERR_OFFLINE
                Return ConstComStr.CAPTION_03_010
            Case ErrorCode.ERR_NOT_EPSON
                Return ConstComStr.CAPTION_03_011
            Case ErrorCode.ERR_WITHOUT_CB
                Return ConstComStr.CAPTION_03_012
            Case ErrorCode.ERR_BUFFER_OVER_FLOW
                Return ConstComStr.CAPTION_03_013
            Case ErrorCode.ERR_REGISTRY
                Return ConstComStr.CAPTION_03_014
            Case ErrorCode.ERR_PAPERINSERT_TIMEOUT
                Return ConstComStr.CAPTION_03_015
            Case ErrorCode.ERR_EXEC_FUNCTION
                Return ConstComStr.CAPTION_03_016
            Case ErrorCode.ERR_EXEC_MICR
                Return ConstComStr.CAPTION_03_017
            Case ErrorCode.ERR_EXEC_SCAN
                Return ConstComStr.CAPTION_03_018
            Case ErrorCode.ERR_RESET
                Return ConstComStr.CAPTION_03_019
            Case ErrorCode.ERR_ABORT
                Return ConstComStr.CAPTION_03_020
            Case ErrorCode.ERR_MICR
                Return ConstComStr.CAPTION_03_021
            Case ErrorCode.ERR_SCAN
                Return ConstComStr.CAPTION_03_022
            Case ErrorCode.ERR_LINE_OVERFLOW
                Return ConstComStr.CAPTION_03_023
            Case ErrorCode.ERR_PAPER_PILED
                Return ConstComStr.CAPTION_03_024
            Case ErrorCode.ERR_PAPER_JAM
                Return ConstComStr.CAPTION_03_025
            Case ErrorCode.ERR_COVER_OPEN
                Return ConstComStr.CAPTION_03_026
            Case ErrorCode.ERR_MICR_NODATA
                Return ConstComStr.CAPTION_03_027
            Case ErrorCode.ERR_MICR_BADDATA
                Return ConstComStr.CAPTION_03_028
            Case ErrorCode.ERR_MICR_NOISE
                Return ConstComStr.CAPTION_03_029
            Case ErrorCode.ERR_SCN_COMPRESS
                Return ConstComStr.CAPTION_03_030
            Case ErrorCode.ERR_PAPER_EXIST
                Return ConstComStr.CAPTION_03_031
            Case ErrorCode.ERR_PAPER_INSERT
                Return ConstComStr.CAPTION_03_032
            Case ErrorCode.ERR_EXEC_SCAN_CHECK_CONTINUOUS
                Return ConstComStr.CAPTION_03_033
            Case ErrorCode.ERR_EXEC_SCAN_CHECK_ONEBYONE
                Return ConstComStr.CAPTION_03_034
            Case ErrorCode.ERR_EXEC_SCAN_IDCARD
                Return ConstComStr.CAPTION_03_035
            Case ErrorCode.ERR_EXEC_PRINT_ROLLPAPER
                Return ConstComStr.CAPTION_03_036
            Case ErrorCode.ERR_EXEC_PRINT_VALIDATION
                Return ConstComStr.CAPTION_03_037
            Case ErrorCode.ERR_THREAD
                Return ConstComStr.CAPTION_03_038
            Case ErrorCode.ERR_IMAGE_FILEOPEN
                Return ConstComStr.CAPTION_03_039
            Case ErrorCode.ERR_IMAGE_UNKNOWNFORMAT
                Return ConstComStr.CAPTION_03_040
            Case ErrorCode.ERR_SIZE
                Return ConstComStr.CAPTION_03_041
            Case ErrorCode.ERR_NOT_FOUND
                Return ConstComStr.CAPTION_03_042
            Case ErrorCode.ERR_NOT_EXEC
                Return ConstComStr.CAPTION_03_043
            Case ErrorCode.ERR_BARCODE_NODATA
                Return ConstComStr.CAPTION_03_044
            Case ErrorCode.ERR_MICR_PARSE
                Return ConstComStr.CAPTION_03_045
            Case ErrorCode.ERR_SCN_IQA
                Return ConstComStr.CAPTION_03_046
            Case ErrorCode.ERR_PRINT_DATA_LENGTH_EXCEED
                Return ConstComStr.CAPTION_03_047
            Case ErrorCode.ERR_PRINT_DATA_UNRECEIVE
                Return ConstComStr.CAPTION_03_048
            Case ErrorCode.ERR_IMAGE_FILEREAD
                Return ConstComStr.CAPTION_03_049
            Case Else
                Return errResultCode.ToString()
        End Select
    End Function
End Class
